### ISSUE TITLE
Need lighter version of installation method + A Docker copy.

### ISSUE THREAD

**Issue by testaccountsnt** [pavanw3b/sh00t#14] opened 2019-02-02 10:21 UTC
The checklist is helpful and complete system efficiently works as a project management tool for penetration testing but code size is 15 MB and dependencies size is 3.5 GB (because of anaconda)

Generally global internal projects are kept on AWS or similar cloud where volume size is not assigned enough. 3.5 GB is for dependencies is more than enough. If one uses Virtualwrapper, dependencies are not exceeding 90 MB as well as large number of projects with great database size can be availed.

Another option can be a docker compose file, where only two containers (one for python and another for postgres) can do the best trick ever. Similar way a docker image can be created in repository and once user pulls it, all it needed to run the container on 8000 port and web application can be accessed easily.

Using this great application with Anaconda is suppressing its advantages. It is very light and very useful but not with anaconda.

Thanks for making it.

**Comment by pavanw3b** [comment] 2019-02-04 03:04
Hey @testaccountsnt,
Thanks for the feedback. I agree with your statements. I chose Anaconda because I hit some issues in virtualenv when testing multiple platforms - especially windows. It's miniconda, the lighter version of anaconda. I haven't the checked the size of it, I'll take look at and consider a better option this week.
Yep, docker is a good option too. It's in our backlog. We tried creating an image, need some final round of testing. Targeting to roll out in sometime.

We're only a few people, and looking for contributors. Let me know if you like to contribute, we'll be happy to work with you.

Thanks again for helping to make Sh00t better. Expect some features in the following weeks.

Cheers,
Pavan

**Comment by testaccountsnt** [comment] 2019-02-19 13:23
Hi @pavanw3b,

I have created Dockerfile for sh00t docker deployment. There are two Docker files i.e. one with Python 3 image and another with Ubuntu 16.04. As I was concerned about size of installation, Ubuntu 16.04 sh00t image is 550 MB size and Python 3 sh00t image is 1GB size.

Kindly clone the repository
https://github.com/testaccountsnt/docker-sh00t.git
and follow the instructions mentioned in readme file.

I have tested this on Docker version 18.03.0-ce. It appears it is working, if you get any error or issue, please mention.

Thanks

**Comment by pavanw3b** [comment] 2019-03-05 14:51
Hey @testaccountsnt,
Appreciate for your contribution. I'll take a look and merge. Thank you!

**Comment by noraj** [comment] 2019-06-02 16:33
@testaccountsnt your issue is a duplicate of #9

**Comment by pavanw3b** [comment] 2019-06-11 19:18
This has been addressed. The latest installation relies on Docker and alternative installation uses virtualenv.

**Closed by pavanw3b** 2019-06-11 19:18 UTC
